<?xml version="1.0"?>
<!DOCTYPE movies [
<!ELEMENT movies (movie+)>
<!ELEMENT movie (name, release, imdb, boxoffice, credits)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT release (#PCDATA)>
<!ELEMENT imdb (#PCDATA)>
<!ELEMENT boxoffice (#PCDATA)>
<!ELEMENT credits (#PCDATA)>
<!ENTITY msg 'John Doe'>

<!ATTLIST movie out (yes|no) "no">
<!ATTLIST name lang CDATA #IMPLIED>
]>

<movies>
    <movie out="yes">
        <name lang="en">Jungle Cruise</name>
        <release>July 30, 2021 (USA)</release>
        <imdb>7.0</imdb>
        <boxoffice>600 M. USD</boxoffice>
        <credits>&msg;</credits>
    </movie>
    <movie out="yes">
        <name lang="en">Spider Man No Way Home</name>
        <release>December 17, 2021 (USA)</release>
        <imdb>8.8</imdb>
        <boxoffice>1.5 B. USD</boxoffice>
        <credits>&msg;</credits>
    </movie>
</movies> 